### ISSUE TITLE
RSS - Render markdown

### ISSUE THREAD

**Issue by guyellis** [guyellis/plant#1221]
RSS is working well.

Noticed a couple of bugs:
1. Need to render the text using the markdown component.
2. Strange `&nbsp;` after the date.

Example text with unrendered markdown:
```
Yesterday I noticed leafhoppers on the Ruby Grape on the Arbor. Today sprayed
 with [Pyrethrin](http://amzn.to/2tFO8dY) with the strongest ...
```

![rss-markdown](https://user-images.githubusercontent.com/2047725/28855818-079bd330-76f4-11e7-8591-9aa9d247b370.png)

**Comment by sprise** [comment]
How to get [rfc 822](https://www.feedvalidator.org/docs/error/InvalidRFC2822Date.html) date for feed? Add something new to utils file?

**Comment by guyellis** [comment]
@sprise thanks for the pointer - didn't know that it had to be rfc 822 - the commit above (already deployed) fixes the date format. However, I'm still seeing the `&nbsp;` in there. Might be a bug in the reader that I'm using. I've installed Slick RSS as a Chrome extension. What does it look like on your reader?

If I use Firefox's built in reader I don't see that `&nbsp;` so I think this is a reader problem...

**Comment by sprise** [comment]
I am using Akgregator and no such &nbsp; occurs. I was half hoping the date adjust would fix it! There are no encoded spaces in the document so I think you are right and this is on Slick RSS.

**Comment by guyellis** [comment]
Okay just tried a couple of Readers and found RSSOwl that appears to do what I need. i.e. does not fetch the page but just shows the results of the feed and that doesn't have the `&nbsp;` in it so I think that problem is Slick RSS.

@sprise did you want to take a crack at Rendering the text with the Markdown component? I think I know what needs to be done if you don't have time or if you want to pair on it...

**Comment by sprise** [comment]
Added Markdown, and also a small max width style to the images for now.

**Comment by guyellis** [comment]
I merged your branch @sprise and that fixes the Markdown to HTML problem. Thanks!
