### ISSUE TITLE
CSV Download

### ISSUE THREAD

**Issue by guyellis** [guyellis/plant#3251]
Allow a selectable list of plant attributes and plants to be downloaded as a CSV.

Include the full URL of the plant in this download.

This will allow somebody to generate 2D barcodes for the links.

A later iteration of this should provide a "Note Adding" link so that the code immediately opens the "Add Note" for that plant.

cc/ @chriscrewdson

**Comment by guyellis** [comment]
@ChrisCrewdson - this is pushed to prod. I just included Name (title), Planted Date and Url in the CSV. Should be trivial to add anything else. LMK what else you'd want in there.

**Comment by ChrisCrewdson** [comment]
Nice. One thing:
The planted date is being in the format "20200128" feels a little odd. Something more like "2020-01-28" would be easier to deal with (for me), even though ISO-8601 technically allows either.

**Comment by guyellis** [comment]
@ChrisCrewdson this is done. You might need to hard refresh the page to get the new bundle.

**Comment by ChrisCrewdson** [comment]
Works great! Nice!
