### ISSUE TITLE
Add UI for Google OAuth Login

### ISSUE THREAD

**Issue by guyellis** [guyellis/plant#428]
* In `/app/components/auth/Login.jsx copy the facebook `home-subheader` div and replace `facebook` with `google`.
* Find a `Login with Google` image similar to the facebook one and put it in `/img/`

**Comment by sprise** [comment]
Shall I upload the new branch for #428 to a new repo such as sprise/plant or here?

**Comment by guyellis** [comment]
Here is the easiest because you are a contributor to this repo. If you weren't a contributor then you'd need to fork it to sprise/plant but that's not necessary in this case.

**Comment by guyellis** [comment]
Should be working now at https://plaaant.com
