### ISSUE TITLE
Image orientation

### ISSUE THREAD

**Issue by guyellis** [guyellis/plant#452]
Images aren't always correctly oriented. More details about why here: http://stackoverflow.com/questions/24658365/img-tag-displays-wrong-orientation

**Comment by guyellis** [comment]
@robrich @Ellisande @sprise have any of you seen this before and found a solution for it?

[Here is an example](https://plaaant.com/plant/southern-blush-mango/57c6567d895a290000ebb4ab) of it happening on the site. In Firefox all the images are correctly oriented because of the `image-orientation` Fix added above. That only works for Firefox and is not implemented by Chrome and other browsers.

The obvious solution is to rewrite the image according to the EXIF information. This seems a bit drastic though so I'm wondering if any of you have come across this and have any ideas.

**Comment by Ellisande** [comment]
A simple hack would be to look at the size information of the image, and rotate the image with CSS if its wider than it is tall.

**Comment by Ellisande** [comment]
Something like http://codepen.io/anon/pen/GjJrzv?editors=1111

**Comment by guyellis** [comment]
Fixed by using gm's autoRotate on Lambda.
