### ISSUE TITLE
Sticky footer

### ISSUE THREAD

**Issue by guyellis** [guyellis/plant#498]
Footer strip should only be "sticky" to the bottom of the page if the page is shorter than the viewport. Otherwise the footer should be at the bottom of the page and not visible on long pages.

**Comment by sprise** [comment]
Footer is sticky on branch 498-sticky-footer, last master fetched this am

**Comment by guyellis** [comment]
I see the branch [here](https://github.com/guyellis/plant/commits/498-sticky-footer) but there are no commits from @sprise on it. Are they committed on your local machine but not pushed yet? If you do `git status` it should tell you if there are any commits ready to push.

**Comment by sprise** [comment]
Whoops, I did not pay attention to the css lint output.

**Comment by guyellis** [comment]
Nice work @sprise - I've merged that into master!
